### ISSUE TITLE
Add Text for companies in registration form

### ISSUE THREAD

**Issue by Anna91lena** [jacksbox/wirvsvirus-lokaleunternehmen#23]
**Sie wollen bestehende Daten in Ihrem Unternehmensprofil ändern?**
Dann schreiben Sie uns bitte eine Mail an bleib.lokal2020@gmail.com. Wir nehmen die gewünschten Änderungen gerne für Sie vor!

**Comment by jacksbox** [comment]
solved in https://github.com/jacksbox/wirvsvirus-lokaleunternehmen/commit/df5f0062fffefe7e42862ec7f30c804d324ad385
