### ISSUE TITLE
Adjust notification after customer placed order

### ISSUE THREAD

**Issue by Anna91lena** [jacksbox/wirvsvirus-lokaleunternehmen#26]
Neuer Text:
**Danke, die Bestellung wurde übermittelt!**
Die Bestellung wurde per Mail an Ihr lokales Unternehmen übermittelt. Sie erhalten eine Bestätigungsmail sowie den zu bezahlenden Preis, sobald Ihr lokales Unternehmen Ihre Bestellung geprüft hat.

Sollten Sie weitere Fragen haben, wenden Sie sich gerne an bleib.lokal2020@gmail.com

__________
Außerdem:
Nach erfolgreicher Bestellung eschreint noch der Link auf das Unternehmensregistrierungsformular. Das würde ich an der Stelle inkl. Text glaube ich dann auch raus nehmen.

**Comment by jacksbox** [comment]
solved
