### ISSUE TITLE
set country at the moment as standard in germany when registering

### ISSUE THREAD

**Issue by cranaweeraproject** [jacksbox/wirvsvirus-lokaleunternehmen#36]
I entered an address in Berlin but somehow the system assigns it to US.

We should for now set it standard to germany. Once we should internationalise we can add a country field to the registration form.
![Screenshot 2020-04-05 at 00 03 19](https://user-images.githubusercontent.com/4922728/78503688-7e732180-7768-11ea-853b-025a95b3e237.png)

**Comment by jacksbox** [comment]
This is a backend Issue concerning the Django Admin panel (@bcye).
As the user registration is now done in the frontend this is maybe obsolete?

Closed
