### ISSUE TITLE
add email verification to registration flow

### ISSUE THREAD

**Issue by cranaweeraproject** [jacksbox/wirvsvirus-lokaleunternehmen#38]
We need to add email verification to the registration.

current flow:
1. user submits regisration form
2. user sees registration confirmation page

should be:
1. user submits registration form
2. users sees an information page that we send a mail
2a. at the same time we send a mail to the user with a verification link
3. user clicks on the verification link
4. user sees registration confirmation page

Texts still to be defined when we want to do it

**Comment by jacksbox** [comment]
Please add this issue in the backend repo.
https://github.com/bcye/lokalshoppen

closed
